server.port=8080
spring.application.name=estatistik-core
logging.level.de.datenmonster=INFO
# Aus Env-Variablen (gesetzt durch Plugin Manager)
plugin.id=${PLUGIN_ID:estatistik-core}
plugin.manager.url=${PLUGIN_MANAGER_URL:http://plugin-manager:9001}
